# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('companyId', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('companyCreateDate', models.DateField(default='2016-08-26')),
                ('companyUpdateDate', models.DateTimeField(default='2016-08-26')),
                ('companyName', models.TextField(max_length=200)),
                ('companyNature', models.TextField(max_length=200)),
                ('companyAddress', models.TextField(max_length=500)),
                ('companyRegisteredDate', models.DateField(verbose_name='registered date')),
                ('industry', models.TextField(max_length=20)),
                ('registeredCaptital', models.FloatField()),
                ('legalRepresentative', models.TextField(max_length=10)),
                ('legalPhone', models.CharField(max_length=50)),
                ('companyAbstract', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('userGroup', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='companydata',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projectm.User'),
        ),
    ]
