# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='companyName',
            field=models.CharField(max_length=200, verbose_name='\u516c\u53f8\u540d\u79f0'),
        ),
    ]
