# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='companyAddress',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='companyName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='companyNature',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='industry',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='legalRepresentative',
            field=models.CharField(max_length=10),
        ),
    ]
