# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectm', '0002_auto_20160830_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='companyAbstract',
            field=models.TextField(verbose_name='\u516c\u53f8\u57fa\u672c\u60c5\u51b5'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='companyAddress',
            field=models.CharField(max_length=500, verbose_name='\u516c\u53f8\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='companyCreateDate',
            field=models.DateField(default=None, verbose_name='\u6210\u7acb\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='companyNature',
            field=models.CharField(choices=[('xxjs', '\u4fe1\u606f\u6280\u672f'), ('swzy', '\u751f\u7269\u5236\u836f')], default='yx', max_length=10, verbose_name='\u516c\u53f8\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='companyRegisteredDate',
            field=models.DateField(verbose_name='\u6ce8\u518c\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='companyUpdateDate',
            field=models.DateTimeField(default=None, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='industry',
            field=models.CharField(choices=[('xxjs', '\u4fe1\u606f\u6280\u672f'), ('swzy', '\u751f\u7269\u5236\u836f')], default='xxjs', max_length=10, verbose_name='\u884c\u4e1a\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='legalPhone',
            field=models.CharField(max_length=50, verbose_name='\u6cd5\u4eba\u8054\u7cfb\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='legalRepresentative',
            field=models.CharField(max_length=10, verbose_name='\u6cd5\u5b9a\u4ee3\u8868\u4eba'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='registeredCaptital',
            field=models.FloatField(verbose_name='\u6ce8\u518c\u8d44\u672c'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('ts', '\u5929\u4f7f\u6295\u8d44\u90e8'), ('ct', '\u521b\u4e1a\u6295\u8d44\u90e8')], default='ts', max_length=10, verbose_name='\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userGroup',
            field=models.CharField(max_length=20, verbose_name='\u804c\u4f4d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
