# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectm', '0002_auto_20160827_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='companyCreateDate',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='companyUpdateDate',
            field=models.DateTimeField(default=None),
        ),
    ]
