# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectm', '0003_auto_20160830_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projectm.User', verbose_name='\u5165\u5e93\u4eba'),
        ),
    ]
