# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectm', '0003_auto_20160827_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industryName', models.CharField(max_length=20)),
                ('industryDescibe', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='companydata',
            name='industry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projectm.IndustryType'),
        ),
    ]
