# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectm', '0004_auto_20160830_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='companyCreateDate',
            field=models.DateField(default=None, verbose_name='\u5165\u5e93\u65f6\u95f4'),
        ),
    ]
