# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectm', '0004_auto_20160827_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSituation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financialIndex', models.CharField(choices=[('income', '\u9500\u552e\u6536\u5165'), ('netProfit', '\u51c0\u5229\u6da6')], default='income', max_length=10)),
                ('yearIndex', models.CharField(choices=[('2015', '2015\u5e74'), ('2016', '2016\u5e74')], default='2015', max_length=4)),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectm.CompanyData')),
            ],
        ),
        migrations.AddField(
            model_name='companydata',
            name='financialSituation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projectm.FinancialSituation'),
        ),
    ]
