# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectm', '0005_auto_20160827_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsituation',
            name='financialData',
            field=models.FloatField(default=None),
        ),
    ]
