# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectm', '0006_companydata_companyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='companyFinancialNeeds',
            field=models.TextField(default=None, verbose_name='\u516c\u53f8\u878d\u8d44\u9700\u6c42'),
        ),
        migrations.AddField(
            model_name='companydata',
            name='companyFinancialSituation',
            field=models.TextField(default=None, verbose_name='\u516c\u53f8\u8d22\u52a1\u6307\u6807'),
        ),
        migrations.AddField(
            model_name='companydata',
            name='companyFollowSuggest',
            field=models.CharField(choices=[('ybgz', '\u4e00\u822c\u5173\u6ce8'), ('zdgz', '\u91cd\u70b9\u5173\u6ce8')], default='ybgz', max_length=10, verbose_name='\u8ddf\u8fdb\u5efa\u8bae'),
        ),
        migrations.AddField(
            model_name='companydata',
            name='companyProjectPassDate',
            field=models.DateField(default=None, verbose_name='\u8fc7\u4f1a\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='companydata',
            name='companyProjectSetUpTime',
            field=models.DateField(default=None, verbose_name='\u7acb\u9879\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='companydata',
            name='companyRemarks',
            field=models.TextField(default=None, verbose_name='\u516c\u53f8\u5176\u4ed6\u5907\u6ce8\u60c5\u51b5'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='companyAbstract',
            field=models.TextField(default=None, verbose_name='\u516c\u53f8\u57fa\u672c\u60c5\u51b5'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='companyAddress',
            field=models.CharField(default=None, max_length=500, verbose_name='\u516c\u53f8\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='companyCreateDate',
            field=models.DateField(default=None, verbose_name='\u5165\u5e93\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='companyNature',
            field=models.CharField(choices=[('yx', '\u6709\u9650\u516c\u53f8'), ('gf', '\u80a1\u4efd\u6709\u9650\u516c\u53f8'), ('td', '\u56e2\u961f')], default='yx', max_length=10, verbose_name='\u516c\u53f8\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='companyRegisteredDate',
            field=models.DateField(default=None, verbose_name='\u6ce8\u518c\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='industry',
            field=models.CharField(choices=[('xxjs', '\u65b0\u4e00\u4ee3\u4fe1\u606f\u6280\u672f'), ('swzy', '\u751f\u7269\u5236\u836f'), ('jnhb', '\u8282\u80fd\u73af\u4fdd'), ('zbzz', '\u9ad8\u7aef\u88c5\u5907\u5236\u9020')], default='xxjs', max_length=10, verbose_name='\u884c\u4e1a\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='legalPhone',
            field=models.CharField(default=None, max_length=50, verbose_name='\u6cd5\u4eba\u8054\u7cfb\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='legalRepresentative',
            field=models.CharField(default=None, max_length=10, verbose_name='\u6cd5\u5b9a\u4ee3\u8868\u4eba'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='registeredCaptital',
            field=models.FloatField(default=None, verbose_name='\u6ce8\u518c\u8d44\u672c'),
        ),
    ]
