# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectm', '0006_financialsituation_financialdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='industry',
            field=models.CharField(choices=[('yx', '\u6709\u9650\u516c\u53f8'), ('gf', '\u80a1\u4efd\u6709\u9650\u516c\u53f8')], default='yx', max_length=10),
        ),
    ]
