# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectm', '0007_auto_20160903_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydata',
            name='legalPhone',
        ),
        migrations.RemoveField(
            model_name='companydata',
            name='legalRepresentative',
        ),
        migrations.AddField(
            model_name='companydata',
            name='contactPeople',
            field=models.CharField(default=None, max_length=10, verbose_name='\u8054\u7cfb\u4eba'),
        ),
        migrations.AddField(
            model_name='companydata',
            name='contactPhone',
            field=models.CharField(default=None, max_length=50, verbose_name='\u8054\u7cfb\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='companyFollowSuggest',
            field=models.CharField(choices=[('ybgz', '\u4e00\u822c\u5173\u6ce8'), ('zdgz', '\u91cd\u70b9\u5173\u6ce8'), ('zh', '\u6682\u7f13\u9879\u76ee'), ('lx', '\u7acb\u9879'), ('gh', '\u5df2\u8fc7\u4f1a'), ('ybk', '\u5df2\u62e8\u6b3e')], default='ybgz', max_length=10, verbose_name='\u8ddf\u8fdb\u5efa\u8bae'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='registeredCaptital',
            field=models.CharField(default=None, max_length=100, verbose_name='\u6ce8\u518c\u8d44\u672c'),
        ),
    ]
