# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectm', '0012_auto_20160915_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='companyUpdateDate',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
