# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectm', '0013_auto_20160915_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='user',
            field=models.CharField(default=None, max_length=50, verbose_name='\u5165\u5e93\u4eba'),
        ),
    ]
