# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectm', '0015_auto_20160921_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='companyAddress',
            field=models.CharField(blank=True, default=None, max_length=500, verbose_name='\u516c\u53f8\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='companyRegisteredDate',
            field=models.DateField(blank=True, default=None, verbose_name='\u6ce8\u518c\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='registeredCaptital',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='\u6ce8\u518c\u8d44\u672c'),
        ),
    ]
